version: 2
jobs:
  build:
    docker:
      - image: maven
      - image: mysql
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - checkout
      - run: |
          apt-get update && apt-get install -qq  lsb-release default-mysql-client netcat
      - run: |
          for i in `seq 1 10`;
          do
            nc -z 0.0.0.0 3306 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for MySQL && exit 1
      - run: mysql -h 0.0.0.0 -u root -e 'source src/main/resources/db/create_database.sql'
      - restore_cache:
          key: java-workshop-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: java-workshop-{{ checksum "pom.xml" }}
      - run: mvn test
